# This workflow backs up the .env file to Proton Drive using rclone and GPG encryption
# Make sure to add the following secrets to your repository:
# - RCLONE_CONFIG: The contents of your rclone.conf file (as a single string)
# - GPG_PASSPHRASE: The passphrase for GPG symmetric encryption

name: Backup .env to Proton Drive

on:
  push:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env from secret
        run: echo "${{ secrets.ENV_CONTENTS }}" > .env

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg

      - name: Restore rclone config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      - name: Encrypt .env file
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          if [ -f .env ]; then
            export HASH=$(git rev-parse --short HEAD)
            echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --symmetric --cipher-algo AES256 .env
            mv .env.gpg ".env_$HASH.gpg"
          else
            echo ".env file not found, skipping encryption and upload." && exit 0;
          fi

      - name: Upload encrypted .env to Proton Drive
        run: |
          for f in .env_*.gpg; do
            [ -f "$f" ] && rclone copy "$f" protondrive:backups/inet-ready/;
          done

      - name: Clean up encrypted files
        run: rm -f .env_*.gpg
