name: Daily Historical Weather Update

on:
  schedule:
    # Run once daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-historical-weather-data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Create logs directory
      - name: Create logs directory
        run: |
          mkdir -p src/scripts/logs

      # Step 5: Run the historical weather update script
      - name: Run historical weather update script
        run: python src/scripts/daily_historical_weather_data.py

      # Step 6: Commit and push if there are changes in data files
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Daily update of historical weather data [skip ci]'
          add: 'public/data/historical_weather_data.csv'
