name: Hourly Weather Update

on:
  schedule:
    # Run every hour at the 0 minute mark
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-weather-data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debug and decode Firebase credentials from GitHub Secrets
      - name: Debug and decode Firebase credentials
        run: |
          # Optional: Check the length of the base64 string
          echo "Base64 string length: $(echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" | wc -c)"

          # Decode the base64 string and save to a file
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" | tr -d '\n' | base64 -d > ./firebase_service_account.json

          # Verify the JSON is valid
          cat ./firebase_service_account.json | python -m json.tool || echo "Warning: Invalid JSON format in credentials file"

      # Step 5: Run the weather update script
      - name: Run weather update script
        env:
          FIREBASE_SERVICE_ACCOUNT: ./firebase_service_account.json # Use correct file path
        run: python src/scripts/hourly_heat_index_api.py

      # Step 6: Clean up credentials file
      - name: Clean up credentials
        if: always()
        run: rm -f firebase_service_account.json
